encoding: UTF-8
include:
  - _html
  - _assets
collections:
  slides:
    output: true

title: 'Basi di Dati I'
# - _slides
# defaults:
#   - scope:
#       path: "_slides"
#     values:
#       slides: true
